import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-full bg-red-500 flex justify-center items-center'>
        <div className='text-2xl text-white'>Hello World!</div>
      </main>
    </>
  )
}
